version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ong_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: reporteria_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reporteria_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: ong_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: reporteria_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./database:/database
    entrypoint: ["/app/entrypoint.sh"]

volumes:
  db_data:
