version: '3.9'

services:
  initdb:
    build: ./app/
    command: /bin/sh -c "python db/ddl.py && python db/registros.py"
    volumes:
      - ./app:/app
      - ./database:/database

  db:
    image: postgres:15
    container_name: ong_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: reporteria_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    depends_on:
      - initdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reporteria_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: ong_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: reporteria_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0

volumes:
  db_data:

